### PR TITLE
feat: bulk download

### PR DESCRIPTION
**Pull request by nyxordinal**
Add new feature for bulk download doujins   
Instructions are included in the README file
Issue: #1

### CODE REVIEW

**Comment by sinkaroid** [comment]
Hi @nyxordinal thanks for the pr. That was nice  
But i actually using different flow with nested json file to resolve the bulk downloads so we dont need make changes in the whole sites [here](https://files.pythonhosted.org/packages/40/7e/38fd9e193a616a2dd03fb46fd1f480ef886ecc1f5b08b82a8ccd2eabd56c/tomoe-3.0.11.tar.gz)
```py
## just need adjust 1 arguments
my_parser.add_argument(
        "--bulk", "-bulk", action="store", metavar=("BULK"), type=str
    )
```

The flow:
Screenshot_655  

Then user can make bulk with `tomoe --bulk doujin.json` It's will also can be mixed with other site as well
```js
{
    "book": [
        {
            "nhentai": 255369
        },
        {
            "nhentai": 177013
        },
        {
            "pururin": 47226
        },
        {
            "hentaifox": 59026
        },
        {
            "asmhentai": 311851
        }
    ]
}
```

But looks like this PR is more simple to scale with end user because my thought was used nested list to make bulk download, I guess some users will confused to use them. What do you think? is pr tested already?

**Comment by nyxordinal** [comment]
Your approach is great @sinkaroid, but imo its too much effort from the end-user side. For the sake of simplicity, I think its better to just add support for multiple input parameter.
The code already tested btw

**Review by sinkaroid — CHANGES_REQUESTED** [review]
Need a small changes here, hentai2read seems breaking changes with your new colon arguments and workflows fail, Could you fix the CI for `hentai2read` on Makefile target and bump the `tomoe/__init__.py` version to `3.0.12`.  We will publish to PyPI package as well

**Comment by nyxordinal** [comment]
Makefile updated and version also bumped to `3.0.12`

**Review by sinkaroid — APPROVED** [review]

**Pull request merged**
